In [7]:
print('dsds')

dsds

In [8]:
import pandas as pd
from pathlib import Path

data_dir = Path(r"C:\Users\yiho1\seoul_data\noise_2024")

file_path = data_dir / "120_서울시 IoT 복합 센서(환경정보)_PUBDATA_202411.csv"

df = pd.read_csv(file_path, encoding="cp949")
df.head()

AttributeError: partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)

In [620]:
print(df.columns.tolist())

['모델번호', '시리얼', '측정시간', '지역', '자치구', '행정동', '온도 최대(℃)', '온도 평균(℃)', '온도 최소(℃)', '습도 최대(%)', '습도 평균(%)', '습도 최소(%)', '풍속 최대(m/s)', '풍속 평균(m/s)', '풍속 최소(m/s)', '풍향 최대(m/s)', '풍향 평균(m/s)', '풍향 최소(m/s)', '조도 최대(lux)', '조도 평균(lux)', '조도 최소(lux)', '자외선 최대(UV)', '자외선 평균(UV)', '자외선 최대(UV).1', '소음 최대(dB)', '소음 평균(dB)', '소음 최소(dB)', '진동(x) 최대(mm/s)', '진동(x) 평균(mm/s)', '진동(x) 최소(mm/s)', '진동(y) 최대(mm/s)', '진동(y) 평균(mm/s)', '진동(y) 최소(mm/s)', '진동(z) 최대(mm/s)', '진동(z) 평균(mm/s)', '진동(z) 최소(mm/s)', '흑구온도 최대(℃)', '흑구온도 평균(℃)', '흑구온도 최소(℃)', '이산화질소 최대(ppm)', '이산화질소 평균(ppm)', '이산화질소 최소(ppm)', '일산화탄소 최대(ppm)', '일산화탄소 평균(ppm)', '일산화탄소 최소(ppm)', '이산화황 최대(ppm)', '이산화황 평균(ppm)', '이산화황 최소(ppm)', '암모니아 최대(ppm)', '암모니아 평균(ppm)', '암모니아 최소(ppm)', '황화수소 최대(ppm)', '황화수소 평균(ppm)', '황화수소 최소(ppm)', '오존 최대(ppm)', '오존 평균(ppm)', '오존 최소(ppm)', '등록일시']

In [621]:
df_202401 = df.iloc[:, [2, 3, 4, 25, 28, 31, 34]].copy()
display(df_202401.head())
print(df_202401.shape)

,측정시간,지역,자치구,소음 평균(dB),진동(x) 평균(mm/s),진동(y) 평균(mm/s),진동(z) 평균(mm/s)
0,2024-11-01_00:07:00,parks,Seoul_Grand_Park,45.0,NaN,NaN,NaN
1,2024-11-01_00:07:00,parks,Seoul_Grand_Park,43.0,NaN,NaN,NaN
2,2024-11-01_00:07:00,traditional_markets,Gwangjin-gu,62.0,NaN,NaN,NaN
3,2024-11-01_00:07:00,main_street,Jongno-gu,44.0,NaN,NaN,NaN
4,2024-11-01_00:07:00,main_street,Jung-gu,64.0,NaN,NaN,NaN

(720105, 7)

In [622]:
df_202401["측정시간"] = pd.to_datetime(
    df_202401["측정시간"].str.replace("_", " "),
    errors="coerce")

In [623]:
display(df_202401.head())

,측정시간,지역,자치구,소음 평균(dB),진동(x) 평균(mm/s),진동(y) 평균(mm/s),진동(z) 평균(mm/s)
0,2024-11-01 00:07:00,parks,Seoul_Grand_Park,45.0,NaN,NaN,NaN
1,2024-11-01 00:07:00,parks,Seoul_Grand_Park,43.0,NaN,NaN,NaN
2,2024-11-01 00:07:00,traditional_markets,Gwangjin-gu,62.0,NaN,NaN,NaN
3,2024-11-01 00:07:00,main_street,Jongno-gu,44.0,NaN,NaN,NaN
4,2024-11-01 00:07:00,main_street,Jung-gu,64.0,NaN,NaN,NaN

In [624]:
df_202401.info()

<class 'pandas.DataFrame'>
RangeIndex: 720105 entries, 0 to 720104
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   측정시간            720105 non-null  datetime64[us]
 1   지역              720105 non-null  str
 2   자치구             720105 non-null  str
 3   소음 평균(dB)       693862 non-null  float64
 4   진동(x) 평균(mm/s)  547809 non-null  float64
 5   진동(y) 평균(mm/s)  547809 non-null  float64
 6   진동(z) 평균(mm/s)  547809 non-null  float64
dtypes: datetime64[us](1), float64(4), str(2)
memory usage: 38.5 MB

In [625]:
df_202401["자치구"].unique()

<StringArray>
['Seoul_Grand_Park',      'Gwangjin-gu',        'Jongno-gu',
          'Jung-gu',       'Gangnam-gu',      'Gangdong-gu',
     'Seongdong-gu',       'Yongsan-gu',       'Gangseo-gu',
        'Gwanak-gu',        'Dobong-gu',     'Seodaemun-gu',
        'Songpa-gu',     'Yangcheon-gu',     'Eunpyeong-gu',
        'Seocho-gu',     'Geumcheon-gu',       'Gangbuk-gu',
       'Dongjak-gu',         'Nowon-gu',          'Guro-gu',
  'Yeongdeungpo-gu',      'Jungnang-gu',    'Dongdaemun-gu',
      'Seongbuk-gu',          'Mapo-gu']
Length: 26, dtype: str

In [626]:
df_202401[df_202401["자치구"] == "Seoul_Grand_Park"].count()

측정시간              2533
지역                2533
자치구               2533
소음 평균(dB)         2533
진동(x) 평균(mm/s)       0
진동(y) 평균(mm/s)       0
진동(z) 평균(mm/s)       0
dtype: int64

In [627]:
# 자치구 한글로 맵핑
gu_map = {
    "Jongno-gu": "종로구",
    "Jung-gu": "중구",
    "Yongsan-gu": "용산구",
    "Seongdong-gu": "성동구",
    "Gwangjin-gu": "광진구",
    "Dongdaemun-gu": "동대문구",
    "Jungnang-gu": "중랑구",
    "Seongbuk-gu": "성북구",
    "Gangbuk-gu": "강북구",
    "Dobong-gu": "도봉구",
    "Nowon-gu": "노원구",
    "Eunpyeong-gu": "은평구",
    "Seodaemun-gu": "서대문구",
    "Mapo-gu": "마포구",
    "Yangcheon-gu": "양천구",
    "Gangseo-gu": "강서구",
    "Guro-gu": "구로구",
    "Geumcheon-gu": "금천구",
    "Yeongdeungpo-gu": "영등포구",
    "Dongjak-gu": "동작구",
    "Gwanak-gu": "관악구",
    "Seocho-gu": "서초구",
    "Gangnam-gu": "강남구",
    "Songpa-gu": "송파구",
    "Gangdong-gu": "강동구"
}

df_202401["자치구"] = df_202401["자치구"].map(gu_map)

In [628]:
df_202401.head()

,측정시간,지역,자치구,소음 평균(dB),진동(x) 평균(mm/s),진동(y) 평균(mm/s),진동(z) 평균(mm/s)
0,2024-11-01 00:07:00,parks,NaN,45.0,NaN,NaN,NaN
1,2024-11-01 00:07:00,parks,NaN,43.0,NaN,NaN,NaN
2,2024-11-01 00:07:00,traditional_markets,광진구,62.0,NaN,NaN,NaN
3,2024-11-01 00:07:00,main_street,종로구,44.0,NaN,NaN,NaN
4,2024-11-01 00:07:00,main_street,중구,64.0,NaN,NaN,NaN

In [629]:
df_202401["자치구"].isna().sum()

np.int64(2533)

In [630]:
df_202401 = df_202401.dropna(subset=["자치구"])

In [631]:
df_202401["자치구"].unique()

<StringArray>
[ '광진구',  '종로구',   '중구',  '강남구',  '강동구',  '성동구',  '용산구',  '강서구',  '관악구',
  '도봉구', '서대문구',  '송파구',  '양천구',  '은평구',  '서초구',  '금천구',  '강북구',  '동작구',
  '노원구',  '구로구', '영등포구',  '중랑구', '동대문구',  '성북구',  '마포구']
Length: 25, dtype: str

In [632]:
df_202401["지역"].unique()

<StringArray>
['traditional_markets',         'main_street',               'parks',
    'residential_area',     'industrial_area',     'roads_and_parks',
     'commercial_area',   'public_facilities']
Length: 8, dtype: str

In [633]:
df_202401["지역"].value_counts()

지역
residential_area       509096
roads_and_parks         88638
traditional_markets     32813
industrial_area         29757
main_street             26662
commercial_area         23630
public_facilities        3557
parks                    3419
Name: count, dtype: int64

In [634]:
df_202401["소음 평균(dB)"].isna().sum()

np.int64(26243)

In [635]:
df_202401["진동(x) 평균(mm/s)"].isna().sum()

np.int64(169763)

In [636]:
df_202401["진동(y) 평균(mm/s)"].isna().sum()

np.int64(169763)

In [637]:
df_202401["진동(z) 평균(mm/s)"].isna().sum()

np.int64(169763)

In [638]:
pd.set_option('display.max_rows', None)

In [639]:
noise_avg = (df_202401.groupby(["자치구", "지역"])["소음 평균(dB)"].mean().reset_index())

In [640]:
noise_avg

      자치구                   지역  소음 평균(dB)
0     강남구      industrial_area  54.367872
1     강남구          main_street  59.979620
2     강남구     residential_area  44.237804
3     강남구      roads_and_parks  60.376534
4     강남구  traditional_markets  46.352859
5     강동구      commercial_area  37.681979
6     강동구      industrial_area  44.831476
7     강동구          main_street  64.608498
8     강동구                parks  54.870833
9     강동구     residential_area  52.637484
10    강동구      roads_and_parks  58.995811
11    강동구  traditional_markets  44.417727
12    강북구      commercial_area        NaN
13    강북구                parks  53.672646
14    강북구     residential_area  46.727125
15    강북구      roads_and_parks  50.645708
16    강북구  traditional_markets  49.442623
17    강서구      commercial_area  64.433148
18    강서구      industrial_area  48.098012
19    강서구          main_street  63.619895
20    강서구     residential_area  46.272534
21    강서구      roads_and_parks  51.779412
22    강서구  traditional_markets  44.513539
23    관악구      commercial_area  50.912378
24    관악구      industrial_area  43.714387
25    관악구          main_street  58.537500
26    관악구     residential_area  46.351689
27    관악구      roads_and_parks  50.087121
28    관악구  traditional_markets  49.207376
29    광진구      commercial_area  36.011127
30    광진구          main_street  53.198324
31    광진구     residential_area  46.033142
32    광진구      roads_and_parks  56.428524
33    광진구  traditional_markets  48.618147
34    구로구      commercial_area  43.547354
35    구로구      industrial_area  49.363701
36    구로구     residential_area  46.587085
37    구로구      roads_and_parks  64.009825
38    구로구  traditional_markets  43.542159
39    금천구      commercial_area  54.082569
40    금천구      industrial_area  44.265349
41    금천구    public_facilities  42.854991
42    금천구     residential_area  45.145569
43    금천구      roads_and_parks  47.900566
44    노원구      commercial_area  55.290141
45    노원구      industrial_area  41.417980
46    노원구     residential_area  47.441744
47    노원구      roads_and_parks  53.483388
48    노원구  traditional_markets  40.440559
49    도봉구      commercial_area  55.677330
50    도봉구      industrial_area  44.873093
51    도봉구          main_street  58.319328
52    도봉구     residential_area  46.240943
53    도봉구      roads_and_parks  56.365379
54    도봉구  traditional_markets  42.130545
55   동대문구      commercial_area  50.387232
56   동대문구     residential_area  43.950136
57   동대문구      roads_and_parks  64.133142
58    동작구      commercial_area  47.602241
59    동작구      industrial_area  41.631944
60    동작구     residential_area  49.834881
61    동작구      roads_and_parks  53.865034
62    동작구  traditional_markets  48.696681
63    마포구      commercial_area  53.542420
64    마포구      industrial_area  45.220828
65    마포구          main_street  58.286396
66    마포구     residential_area  46.282695
67    마포구      roads_and_parks  59.331198
68    마포구  traditional_markets  43.519023
69   서대문구      commercial_area  43.944367
70   서대문구    public_facilities  55.330556
71   서대문구     residential_area  45.299644
72   서대문구      roads_and_parks  55.481826
73   서대문구  traditional_markets  54.081250
74    서초구      commercial_area  54.668985
75    서초구      industrial_area  42.084722
76    서초구          main_street  65.494725
77    서초구     residential_area  48.368425
78    서초구      roads_and_parks  51.488952
79    성동구      commercial_area  50.299539
80    성동구      industrial_area  47.712696
81    성동구          main_street  50.911111
82    성동구                parks  59.431280
83    성동구     residential_area  46.300340
84    성동구      roads_and_parks  69.519444
85    성북구      commercial_area        NaN
86    성북구      industrial_area  55.333333
87    성북구     residential_area  46.175286
88    성북구      roads_and_parks  56.662031
89    송파구      commercial_area  47.456963
90    송파구      industrial_area  49.444600
91    송파구                parks  56.458702
92    송파구     residential_area  45.539227
93    송파구      roads_and_parks  55.041511
94    송파구  traditional_markets  55.723120
95    양천구      commercial_area  48.544056
96    양천구      industrial_area  47.086254
97    양천구          main_street  62.951389
98    양천구     residential_area  45.073754
99    양천구      roads_and_parks  60.277256
100   양천구  traditional_markets  43.305809
101  영등포구      commercial_area  48.353025
102  영등포구      industrial_area  46.859064
103  영등포구     residential_area  44.738684
104  영등포구      roads_and_parks  57.038573
105   용산구      commercial_area  43.290682
106   용산구          main_street  55.645833
107   용산구     residential_area  44.650402
108   용산구      roads_and_parks  54.543994
109   은평구      commercial_area  53.950464
110   은평구          main_street  68.444290
111   은평구                parks  58.860918
112   은평구     residential_area  45.658660
113   은평구      roads_and_parks  57.898740
114   종로구          main_street  48.377358
115   종로구    public_facilities  45.353436
116   종로구     residential_area  45.610119
117   종로구      roads_and_parks  57.220747
118    중구      commercial_area  48.887500
119    중구      industrial_area  43.748495
120    중구          main_street  53.543488
121    중구     residential_area  44.114628
122    중구      roads_and_parks  49.374050
123   중랑구      commercial_area  43.994441
124   중랑구      industrial_area  62.243626
125   중랑구     residential_area  45.057493
126   중랑구      roads_and_parks  57.000697
127   중랑구  traditional_markets  41.863445

In [641]:
noise_avg1 = (df_202401.groupby(["지역", "자치구"])["소음 평균(dB)"].mean().reset_index())
noise_avg1.sort_values("소음 평균(dB)", ascending=False)

                      지역   자치구  소음 평균(dB)
103      roads_and_parks   성동구  69.519444
52           main_street   은평구  68.444290
48           main_street   서초구  65.494725
42           main_street   강동구  64.608498
2        commercial_area   강서구  64.433148
98       roads_and_parks  동대문구  64.133142
94       roads_and_parks   구로구  64.009825
43           main_street   강서구  63.619895
50           main_street   양천구  62.951389
40       industrial_area   중랑구  62.243626
88       roads_and_parks   강남구  60.376534
106      roads_and_parks   양천구  60.277256
41           main_street   강남구  59.979620
57                 parks   성동구  59.431280
100      roads_and_parks   마포구  59.331198
89       roads_and_parks   강동구  58.995811
59                 parks   은평구  58.860918
44           main_street   관악구  58.537500
46           main_street   도봉구  58.319328
47           main_street   마포구  58.286396
109      roads_and_parks   은평구  57.898740
110      roads_and_parks   종로구  57.220747
107      roads_and_parks  영등포구  57.038573
112      roads_and_parks   중랑구  57.000697
104      roads_and_parks   성북구  56.662031
58                 parks   송파구  56.458702
93       roads_and_parks   광진구  56.428524
97       roads_and_parks   도봉구  56.365379
125  traditional_markets   송파구  55.723120
8        commercial_area   도봉구  55.677330
51           main_street   용산구  55.645833
101      roads_and_parks  서대문구  55.481826
35       industrial_area   성북구  55.333333
61     public_facilities  서대문구  55.330556
7        commercial_area   노원구  55.290141
105      roads_and_parks   송파구  55.041511
55                 parks   강동구  54.870833
13       commercial_area   서초구  54.668985
108      roads_and_parks   용산구  54.543994
23       industrial_area   강남구  54.367872
6        commercial_area   금천구  54.082569
124  traditional_markets  서대문구  54.081250
20       commercial_area   은평구  53.950464
99       roads_and_parks   동작구  53.865034
56                 parks   강북구  53.672646
54           main_street    중구  53.543488
11       commercial_area   마포구  53.542420
96       roads_and_parks   노원구  53.483388
45           main_street   광진구  53.198324
64      residential_area   강동구  52.637484
91       roads_and_parks   강서구  51.779412
102      roads_and_parks   서초구  51.488952
3        commercial_area   관악구  50.912378
49           main_street   성동구  50.911111
90       roads_and_parks   강북구  50.645708
9        commercial_area  동대문구  50.387232
14       commercial_area   성동구  50.299539
92       roads_and_parks   관악구  50.087121
74      residential_area   동작구  49.834881
36       industrial_area   송파구  49.444600
115  traditional_markets   강북구  49.442623
111      roads_and_parks    중구  49.374050
27       industrial_area   구로구  49.363701
117  traditional_markets   관악구  49.207376
21       commercial_area    중구  48.887500
122  traditional_markets   동작구  48.696681
118  traditional_markets   광진구  48.618147
17       commercial_area   양천구  48.544056
53           main_street   종로구  48.377358
77      residential_area   서초구  48.368425
18       commercial_area  영등포구  48.353025
25       industrial_area   강서구  48.098012
95       roads_and_parks   금천구  47.900566
34       industrial_area   성동구  47.712696
10       commercial_area   동작구  47.602241
16       commercial_area   송파구  47.456963
71      residential_area   노원구  47.441744
37       industrial_area   양천구  47.086254
38       industrial_area  영등포구  46.859064
65      residential_area   강북구  46.727125
69      residential_area   구로구  46.587085
113  traditional_markets   강남구  46.352859
67      residential_area   관악구  46.351689
78      residential_area   성동구  46.300340
75      residential_area   마포구  46.282695
66      residential_area   강서구  46.272534
72      residential_area   도봉구  46.240943
79      residential_area   성북구  46.175286
68      residential_area   광진구  46.033142
84      residential_area   은평구  45.658660
85      residential_area   종로구  45.610119
80      residential_area   송파구  45.539227
62     public_facilities   종로구  45.353436
76      residential_area  서대문구  45.299644
32       industrial_area   마포구  45.220828
70      residential_area   금천구  45.145569
81      residential_area   양천구  45.073754
87      residential_area   중랑구  45.057493
30       industrial_area   도봉구  44.873093
24       industrial_area   강동구  44.831476
82      residential_area  영등포구  44.738684
83      residential_area   용산구  44.650402
116  traditional_markets   강서구  44.513539
114  traditional_markets   강동구  44.417727
28       industrial_area   금천구  44.265349
63      residential_area   강남구  44.237804
86      residential_area    중구  44.114628
22       commercial_area   중랑구  43.994441
73      residential_area  동대문구  43.950136
12       commercial_area  서대문구  43.944367
39       industrial_area    중구  43.748495
26       industrial_area   관악구  43.714387
5        commercial_area   구로구  43.547354
119  traditional_markets   구로구  43.542159
123  traditional_markets   마포구  43.519023
126  traditional_markets   양천구  43.305809
19       commercial_area   용산구  43.290682
60     public_facilities   금천구  42.854991
121  traditional_markets   도봉구  42.130545
33       industrial_area   서초구  42.084722
127  traditional_markets   중랑구  41.863445
31       industrial_area   동작구  41.631944
29       industrial_area   노원구  41.417980
120  traditional_markets   노원구  40.440559
0        commercial_area   강동구  37.681979
4        commercial_area   광진구  36.011127
1        commercial_area   강북구        NaN
15       commercial_area   성북구        NaN

In [642]:
noise_avg2 = (df_202401.groupby(["지역"])["소음 평균(dB)"].mean().reset_index())
noise_avg2.sort_values("소음 평균(dB)", ascending=False)

                    지역  소음 평균(dB)
2          main_street  58.039510
3                parks  56.634689
6      roads_and_parks  56.127196
0      commercial_area  48.462811
1      industrial_area  46.663828
5     residential_area  46.506011
7  traditional_markets  45.953645
4    public_facilities  45.881080

In [643]:
noise_avg3 = (df_202401.groupby(["자치구"])["소음 평균(dB)"].mean().reset_index())
noise_avg3.sort_values("소음 평균(dB)", ascending=False)

     자치구  소음 평균(dB)
1    강동구  52.734410
14   서초구  50.772699
11   동작구  49.723168
0    강남구  49.720570
12   마포구  48.896452
21   은평구  48.714278
13  서대문구  48.687314
3    강서구  48.484196
5    광진구  47.865269
8    노원구  47.809953
22   종로구  47.766172
2    강북구  47.755799
9    도봉구  47.702943
6    구로구  47.418581
24   중랑구  47.344321
19  영등포구  47.343042
17   송파구  47.257583
23    중구  47.131605
15   성동구  47.048345
16   성북구  47.037837
4    관악구  46.750350
18   양천구  46.335569
10  동대문구  46.299407
7    금천구  46.158133
20   용산구  45.915823

In [644]:
vibration_avg = (df_202401.groupby(["자치구"])[["진동(x) 평균(mm/s)", "진동(y) 평균(mm/s)", "진동(z) 평균(mm/s)"]].mean().reset_index())

In [645]:
vibration_avg.sort_values("진동(z) 평균(mm/s)", ascending=False)

     자치구  진동(x) 평균(mm/s)  진동(y) 평균(mm/s)  진동(z) 평균(mm/s)
19  영등포구        0.027498        0.058829        1.043955
10  동대문구        0.028287        0.065255        1.042966
21   은평구        0.028896        0.058387        1.038420
22   종로구        0.029718        0.045098        1.037849
5    광진구        0.030016        0.061093        1.033652
18   양천구        0.026882        0.056906        1.033087
24   중랑구        0.031504        0.075951        1.032834
2    강북구        0.027076        0.054171        1.032661
7    금천구        0.021555        0.054277        1.032154
12   마포구        0.030745        0.062877        1.031844
14   서초구        0.022566        0.067116        1.030665
13  서대문구        0.027844        0.059305        1.029602
4    관악구        0.026311        0.055569        1.029248
15   성동구        0.027610        0.061040        1.028999
16   성북구        0.023872        0.059320        1.028074
9    도봉구        0.024531        0.069954        1.027872
20   용산구        0.022701        0.060523        1.026247
11   동작구        0.028672        0.066434        1.021227
0    강남구        0.026662        0.057145        1.012895
17   송파구        0.028071        0.054081        1.011456
1    강동구        0.027618        0.055365        1.009232
6    구로구        0.028639        0.062395        0.996940
23    중구        0.021419        0.066447        0.995186
8    노원구        0.026673        0.061946        0.981081
3    강서구        0.039025        0.052247        0.975779

In [646]:
vibration_avg1 = (df_202401.groupby(["자치구", "지역"])[["진동(x) 평균(mm/s)", "진동(y) 평균(mm/s)", "진동(z) 평균(mm/s)"]].mean().reset_index())

In [647]:
vibration_avg1

      자치구                   지역  진동(x) 평균(mm/s)  진동(y) 평균(mm/s)  진동(z) 평균(mm/s)
0     강남구      industrial_area        0.024986        0.052128        1.033150
1     강남구          main_street             NaN             NaN             NaN
2     강남구     residential_area        0.028974        0.052720        1.001510
3     강남구      roads_and_parks        0.023964        0.075598        1.030963
4     강남구  traditional_markets        0.011527        0.072538        1.067545
5     강동구      commercial_area        0.018173        0.026248        1.050628
6     강동구      industrial_area        0.104318        0.070891        1.068036
7     강동구          main_street             NaN             NaN             NaN
8     강동구                parks             NaN             NaN             NaN
9     강동구     residential_area        0.026390        0.051895        1.001917
10    강동구      roads_and_parks        0.030131        0.046029        1.034549
11    강동구  traditional_markets        0.017199        0.107317        1.041037
12    강북구      commercial_area             NaN             NaN             NaN
13    강북구                parks             NaN             NaN             NaN
14    강북구     residential_area        0.024821        0.045796        1.037261
15    강북구      roads_and_parks        0.041469        0.078942        1.026050
16    강북구  traditional_markets        0.022240        0.070675        1.015189
17    강서구      commercial_area             NaN             NaN             NaN
18    강서구      industrial_area        0.052264        0.015984        0.802036
19    강서구          main_street             NaN             NaN             NaN
20    강서구     residential_area        0.025521        0.055954        0.986691
21    강서구      roads_and_parks        0.180371        0.073259        1.024252
22    강서구  traditional_markets        0.019537        0.038647        1.033394
23    관악구      commercial_area        0.010000        0.022809        1.062100
24    관악구      industrial_area        0.023466        0.041665        1.050829
25    관악구          main_street             NaN             NaN             NaN
26    관악구     residential_area        0.026032        0.054643        1.027975
27    관악구      roads_and_parks        0.019486        0.050375        1.046736
28    관악구  traditional_markets        0.047933        0.112171        1.015832
29    광진구      commercial_area        0.020000        0.050932        1.074854
30    광진구          main_street             NaN             NaN             NaN
31    광진구     residential_area        0.031176        0.061426        1.030730
32    광진구      roads_and_parks        0.035371        0.055748        1.030336
33    광진구  traditional_markets        0.020272        0.068815        1.040049
34    구로구      commercial_area        0.010808        0.036281        1.058649
35    구로구      industrial_area        0.016190        0.067096        1.057252
36    구로구     residential_area        0.032950        0.072833        0.966972
37    구로구      roads_and_parks        0.027458        0.029312        1.049846
38    구로구  traditional_markets        0.023198        0.044916        1.043583
39    금천구      commercial_area        0.030966        0.083608        1.013338
40    금천구      industrial_area        0.038151        0.037212        1.041736
41    금천구    public_facilities        0.028663        0.043286        1.051591
42    금천구     residential_area        0.016756        0.054304        1.022461
43    금천구      roads_and_parks        0.013362        0.066893        1.039098
44    노원구      commercial_area        0.042479        0.015535        1.055296
45    노원구      industrial_area        0.016552        0.031501        1.006460
46    노원구     residential_area        0.026618        0.073778        0.965420
47    노원구      roads_and_parks        0.032275        0.036222        1.009682
48    노원구  traditional_markets        0.023378        0.076741        0.988566
49    도봉구      commercial_area        0.045202        0.133157        1.049291
50    도봉구      industrial_area        0.015227        0.053161        1.046574
51    도봉구          main_street             NaN             NaN             NaN
52    도봉구     residential_area        0.023796        0.076972        1.019359
53    도봉구      roads_and_parks        0.065030        0.060984        1.089478
54    도봉구  traditional_markets        0.014895        0.040337        1.025273
55   동대문구      commercial_area        0.032227        0.059035        1.064646
56   동대문구     residential_area        0.027666        0.066235        1.039550
57   동대문구      roads_and_parks             NaN             NaN             NaN
58    동작구      commercial_area        0.022955        0.035448        1.070350
59    동작구      industrial_area        0.022389        0.030097        1.020431
60    동작구     residential_area        0.032381        0.069602        1.019579
61    동작구      roads_and_parks        0.012399        0.090389        1.014124
62    동작구  traditional_markets        0.027884        0.061324        1.018271
63    마포구      commercial_area        0.012337        0.133394        1.008387
64    마포구      industrial_area        0.031046        0.056220        1.005314
65    마포구          main_street             NaN             NaN             NaN
66    마포구     residential_area        0.031270        0.065981        1.033675
67    마포구      roads_and_parks        0.030142        0.052219        1.034633
68    마포구  traditional_markets        0.032107        0.049098        1.018999
69   서대문구      commercial_area        0.020070        0.043143        1.008373
70   서대문구    public_facilities             NaN             NaN             NaN
71   서대문구     residential_area        0.028842        0.061014        1.032623
72   서대문구      roads_and_parks        0.021599        0.051460        1.008414
73   서대문구  traditional_markets             NaN             NaN             NaN
74    서초구      commercial_area        0.065702        0.045716        1.074590
75    서초구      industrial_area        0.014667        0.072826        1.016049
76    서초구          main_street             NaN             NaN             NaN
77    서초구     residential_area        0.019840        0.071463        1.031970
78    서초구      roads_and_parks        0.026540        0.051228        1.020889
79    성동구      commercial_area        0.029831        0.075253        0.989739
80    성동구      industrial_area        0.026612        0.039193        1.006943
81    성동구          main_street             NaN             NaN             NaN
82    성동구                parks             NaN             NaN             NaN
83    성동구     residential_area        0.027648        0.062464        1.031364
84    성동구      roads_and_parks             NaN             NaN             NaN
85    성북구      commercial_area             NaN             NaN             NaN
86    성북구      industrial_area             NaN             NaN             NaN
87    성북구     residential_area        0.023872        0.059320        1.028074
88    성북구      roads_and_parks             NaN             NaN             NaN
89    송파구      commercial_area        0.040713        0.051580        1.026217
90    송파구      industrial_area        0.078962        0.062286        1.038541
91    송파구                parks             NaN             NaN             NaN
92    송파구     residential_area        0.027295        0.052564        1.001398
93    송파구      roads_and_parks        0.015354        0.033181        1.061684
94    송파구  traditional_markets        0.020372        0.106156        1.054413
95    양천구      commercial_area        0.010140        0.033552        1.078895
96    양천구      industrial_area        0.023503        0.067407        1.022172
97    양천구          main_street             NaN             NaN             NaN
98    양천구     residential_area        0.027666        0.057146        1.034749
99    양천구      roads_and_parks        0.013361        0.053125        1.023917
100   양천구  traditional_markets        0.025974        0.050574        1.008265
101  영등포구      commercial_area        0.020043        0.063960        1.026248
102  영등포구      industrial_area        0.019842        0.052745        1.065902
103  영등포구     residential_area        0.030555        0.056738        1.037471
104  영등포구      roads_and_parks        0.025290        0.069271        1.070132
105   용산구      commercial_area        0.028547        0.037969        1.003950
106   용산구          main_street             NaN             NaN             NaN
107   용산구     residential_area        0.022049        0.061525        1.029567
108   용산구      roads_and_parks        0.021966        0.089073        1.014916
109   은평구      commercial_area             NaN             NaN             NaN
110   은평구          main_street             NaN             NaN             NaN
111   은평구                parks             NaN             NaN             NaN
112   은평구     residential_area        0.029344        0.058422        1.038776
113   은평구      roads_and_parks        0.020696        0.057744        1.031908
114   종로구          main_street             NaN             NaN             NaN
115   종로구    public_facilities        0.021038        0.043184        1.102286
116   종로구     residential_area        0.030489        0.042523        1.035804
117   종로구      roads_and_parks        0.011056        0.138437        1.045775
118    중구      commercial_area        0.020389        0.044222        0.998750
119    중구      industrial_area        0.023349        0.094803        1.020384
120    중구          main_street             NaN             NaN             NaN
121    중구     residential_area        0.021265        0.064244        0.971783
122    중구      roads_and_parks        0.021032        0.061797        1.043081
123   중랑구      commercial_area        0.046894        0.031202        1.026206
124   중랑구      industrial_area             NaN             NaN             NaN
125   중랑구     residential_area        0.028931        0.072995        1.033786
126   중랑구      roads_and_parks        0.061604        0.149679        1.065188
127   중랑구  traditional_markets        0.020000        0.105987        1.016190

In [648]:
vibration_avg1["지역"].unique()

<StringArray>
[    'industrial_area',         'main_street',    'residential_area',
     'roads_and_parks', 'traditional_markets',     'commercial_area',
               'parks',   'public_facilities']
Length: 8, dtype: str

In [649]:
vibration_avg1[vibration_avg1["지역"] == "industrial_area"].info()
vibration_avg1[vibration_avg1["지역"] == "main_street"].info()

<class 'pandas.DataFrame'>
Index: 18 entries, 0 to 124
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   자치구             18 non-null     str
 1   지역              18 non-null     str
 2   진동(x) 평균(mm/s)  16 non-null     float64
 3   진동(y) 평균(mm/s)  16 non-null     float64
 4   진동(z) 평균(mm/s)  16 non-null     float64
dtypes: float64(3), str(2)
memory usage: 864.0 bytes
<class 'pandas.DataFrame'>
Index: 14 entries, 1 to 120
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   자치구             14 non-null     str
 1   지역              14 non-null     str
 2   진동(x) 평균(mm/s)  0 non-null      float64
 3   진동(y) 평균(mm/s)  0 non-null      float64
 4   진동(z) 평균(mm/s)  0 non-null      float64
dtypes: float64(3), str(2)
memory usage: 672.0 bytes

In [650]:
vibration_avg1[vibration_avg1["지역"] == "residential_area"].info()
vibration_avg1[vibration_avg1["지역"] == "roads_and_parks"].info()

<class 'pandas.DataFrame'>
Index: 25 entries, 2 to 125
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   자치구             25 non-null     str
 1   지역              25 non-null     str
 2   진동(x) 평균(mm/s)  25 non-null     float64
 3   진동(y) 평균(mm/s)  25 non-null     float64
 4   진동(z) 평균(mm/s)  25 non-null     float64
dtypes: float64(3), str(2)
memory usage: 1.2 KB
<class 'pandas.DataFrame'>
Index: 25 entries, 3 to 126
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   자치구             25 non-null     str
 1   지역              25 non-null     str
 2   진동(x) 평균(mm/s)  22 non-null     float64
 3   진동(y) 평균(mm/s)  22 non-null     float64
 4   진동(z) 평균(mm/s)  22 non-null     float64
dtypes: float64(3), str(2)
memory usage: 1.2 KB

In [651]:
vibration_avg1[vibration_avg1["지역"] == "traditional_markets"].info()
vibration_avg1[vibration_avg1["지역"] == "commercial_area"].info()

<class 'pandas.DataFrame'>
Index: 15 entries, 4 to 127
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   자치구             15 non-null     str
 1   지역              15 non-null     str
 2   진동(x) 평균(mm/s)  14 non-null     float64
 3   진동(y) 평균(mm/s)  14 non-null     float64
 4   진동(z) 평균(mm/s)  14 non-null     float64
dtypes: float64(3), str(2)
memory usage: 720.0 bytes
<class 'pandas.DataFrame'>
Index: 23 entries, 5 to 123
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   자치구             23 non-null     str
 1   지역              23 non-null     str
 2   진동(x) 평균(mm/s)  19 non-null     float64
 3   진동(y) 평균(mm/s)  19 non-null     float64
 4   진동(z) 평균(mm/s)  19 non-null     float64
dtypes: float64(3), str(2)
memory usage: 1.1 KB

In [652]:
vibration_avg1[vibration_avg1["지역"] == "parks"].info()
vibration_avg1[vibration_avg1["지역"] == "public_facilities"].info()

<class 'pandas.DataFrame'>
Index: 5 entries, 8 to 111
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   자치구             5 non-null      str
 1   지역              5 non-null      str
 2   진동(x) 평균(mm/s)  0 non-null      float64
 3   진동(y) 평균(mm/s)  0 non-null      float64
 4   진동(z) 평균(mm/s)  0 non-null      float64
dtypes: float64(3), str(2)
memory usage: 240.0 bytes
<class 'pandas.DataFrame'>
Index: 3 entries, 41 to 115
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   자치구             3 non-null      str
 1   지역              3 non-null      str
 2   진동(x) 평균(mm/s)  2 non-null      float64
 3   진동(y) 평균(mm/s)  2 non-null      float64
 4   진동(z) 평균(mm/s)  2 non-null      float64
dtypes: float64(3), str(2)
memory usage: 144.0 bytes

In [653]:
df_202401_copy = df_202401.copy()

In [654]:
df_202401_copy = df_202401_copy.drop(df_202401[df_202401["지역"].isin(["parks", "main_street"])].index)

In [655]:
df_202401_copy["진동(x) 평균(mm/s)"].isna().sum()

np.int64(139682)

In [656]:
df_202401_copy["진동(y) 평균(mm/s)"].isna().sum()

np.int64(139682)

In [657]:
df_202401_copy["진동(z) 평균(mm/s)"].isna().sum()

np.int64(139682)

In [658]:
missing_vibration = df_202401[[
    "진동(x) 평균(mm/s)",
    "진동(y) 평균(mm/s)",
    "진동(z) 평균(mm/s)"
]].isnull().groupby(df_202401["지역"]).sum()

missing_vibration.sort_values("진동(x) 평균(mm/s)", ascending=False)

                     진동(x) 평균(mm/s)  진동(y) 평균(mm/s)  진동(z) 평균(mm/s)
지역
residential_area              81757           81757           81757
roads_and_parks               43256           43256           43256
main_street                   26662           26662           26662
commercial_area                5098            5098            5098
traditional_markets            4924            4924            4924
industrial_area                3927            3927            3927
parks                          3419            3419            3419
public_facilities               720             720             720

In [659]:
missing_by_gu = df_202401[[
    "자치구",
    "진동(x) 평균(mm/s)",
    "진동(y) 평균(mm/s)",
    "진동(z) 평균(mm/s)"
]].isnull().groupby(df_202401["자치구"]).sum()

missing_by_gu.sort_values("진동(x) 평균(mm/s)", ascending=False)

      자치구  진동(x) 평균(mm/s)  진동(y) 평균(mm/s)  진동(z) 평균(mm/s)
자치구
강동구     0           23278           23278           23278
강서구     0           14684           14684           14684
도봉구     0           11399           11399           11399
강남구     0           10569           10569           10569
서초구     0            9570            9570            9570
종로구     0            9304            9304            9304
서대문구    0            8619            8619            8619
은평구     0            7874            7874            7874
중구      0            7848            7848            7848
동작구     0            7840            7840            7840
성동구     0            6391            6391            6391
강북구     0            6389            6389            6389
양천구     0            6161            6161            6161
관악구     0            4507            4507            4507
광진구     0            4363            4363            4363
성북구     0            4274            4274            4274
중랑구     0            4146            4146            4146
마포구     0            3944            3944            3944
구로구     0            3545            3545            3545
송파구     0            2895            2895            2895
노원구     0            2839            2839            2839
동대문구    0            2837            2837            2837
영등포구    0            2344            2344            2344
용산구     0            2158            2158            2158
금천구     0            1985            1985            1985

In [660]:
df.head()

,모델번호,시리얼,측정시간,지역,자치구,행정동,온도 최대(℃),온도 평균(℃),온도 최소(℃),습도 최대(%),...,암모니아 최대(ppm),암모니아 평균(ppm),암모니아 최소(ppm),황화수소 최대(ppm),황화수소 평균(ppm),황화수소 최소(ppm),오존 최대(ppm),오존 평균(ppm),오존 최소(ppm),등록일시
0,SDOT001,OC3CL200010,2024-11-01_00:07:00,parks,Seoul_Grand_Park,meeting_bridge2,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,2024-11-01 0:07
1,SDOT001,OC3CL200011,2024-11-01_00:07:00,parks,Seoul_Grand_Park,valet_parking1,12.4,12.1,11.8,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,2024-11-01 0:07
2,SDOT001,OC3CL200012,2024-11-01_00:07:00,traditional_markets,Gwangjin-gu,Hwayang-dong,16.9,16.7,16.5,83.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,2024-11-01 0:07
3,SDOT001,OC3CL200013,2024-11-01_00:07:00,main_street,Jongno-gu,Samcheong-dong,14.4,14.2,14.0,69.0,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,2024-11-01 0:07
4,SDOT001,OC3CL200014,2024-11-01_00:07:00,main_street,Jung-gu,Myeong-dong,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,2024-11-01 0:07

In [661]:
df_corr = df_202401[[
    "소음 평균(dB)",
    "진동(x) 평균(mm/s)",
    "진동(y) 평균(mm/s)",
    "진동(z) 평균(mm/s)"
]].dropna()

df_corr.corr()

                소음 평균(dB)  진동(x) 평균(mm/s)  진동(y) 평균(mm/s)  진동(z) 평균(mm/s)
소음 평균(dB)        1.000000       -0.012268       -0.022158       -0.025572
진동(x) 평균(mm/s)  -0.012268        1.000000       -0.011114        0.053407
진동(y) 평균(mm/s)  -0.022158       -0.011114        1.000000        0.142618
진동(z) 평균(mm/s)  -0.025572        0.053407        0.142618        1.000000

In [662]:
df_202401.groupby("지역")[[
    "소음 평균(dB)",
    "진동(x) 평균(mm/s)"
]].corr()

                                    소음 평균(dB)  진동(x) 평균(mm/s)
지역
commercial_area     소음 평균(dB)        1.000000        0.179082
                    진동(x) 평균(mm/s)   0.179082        1.000000
industrial_area     소음 평균(dB)        1.000000       -0.045877
                    진동(x) 평균(mm/s)  -0.045877        1.000000
main_street         소음 평균(dB)        1.000000             NaN
                    진동(x) 평균(mm/s)        NaN             NaN
parks               소음 평균(dB)        1.000000             NaN
                    진동(x) 평균(mm/s)        NaN             NaN
public_facilities   소음 평균(dB)        1.000000        0.127179
                    진동(x) 평균(mm/s)   0.127179        1.000000
residential_area    소음 평균(dB)        1.000000       -0.042719
                    진동(x) 평균(mm/s)  -0.042719        1.000000
roads_and_parks     소음 평균(dB)        1.000000        0.121132
                    진동(x) 평균(mm/s)   0.121132        1.000000
traditional_markets 소음 평균(dB)        1.000000       -0.010231
                    진동(x) 평균(mm/s)  -0.010231        1.000000

In [663]:
df_202401.groupby("자치구")[[
    "소음 평균(dB)",
    "진동(x) 평균(mm/s)"
]].corr()

                     소음 평균(dB)  진동(x) 평균(mm/s)
자치구
강남구  소음 평균(dB)        1.000000       -0.081214
     진동(x) 평균(mm/s)  -0.081214        1.000000
강동구  소음 평균(dB)        1.000000       -0.115481
     진동(x) 평균(mm/s)  -0.115481        1.000000
강북구  소음 평균(dB)        1.000000        0.449326
     진동(x) 평균(mm/s)   0.449326        1.000000
강서구  소음 평균(dB)        1.000000       -0.082861
     진동(x) 평균(mm/s)  -0.082861        1.000000
관악구  소음 평균(dB)        1.000000        0.014132
     진동(x) 평균(mm/s)   0.014132        1.000000
광진구  소음 평균(dB)        1.000000       -0.012569
     진동(x) 평균(mm/s)  -0.012569        1.000000
구로구  소음 평균(dB)        1.000000        0.140288
     진동(x) 평균(mm/s)   0.140288        1.000000
금천구  소음 평균(dB)        1.000000       -0.256061
     진동(x) 평균(mm/s)  -0.256061        1.000000
노원구  소음 평균(dB)        1.000000       -0.124695
     진동(x) 평균(mm/s)  -0.124695        1.000000
도봉구  소음 평균(dB)        1.000000        0.413483
     진동(x) 평균(mm/s)   0.413483        1.000000
동대문구 소음 평균(dB)        1.000000        0.002607
     진동(x) 평균(mm/s)   0.002607        1.000000
동작구  소음 평균(dB)        1.000000       -0.157244
     진동(x) 평균(mm/s)  -0.157244        1.000000
마포구  소음 평균(dB)        1.000000       -0.000516
     진동(x) 평균(mm/s)  -0.000516        1.000000
서대문구 소음 평균(dB)        1.000000       -0.128077
     진동(x) 평균(mm/s)  -0.128077        1.000000
서초구  소음 평균(dB)        1.000000        0.315928
     진동(x) 평균(mm/s)   0.315928        1.000000
성동구  소음 평균(dB)        1.000000       -0.122281
     진동(x) 평균(mm/s)  -0.122281        1.000000
성북구  소음 평균(dB)        1.000000        0.088399
     진동(x) 평균(mm/s)   0.088399        1.000000
송파구  소음 평균(dB)        1.000000       -0.013835
     진동(x) 평균(mm/s)  -0.013835        1.000000
양천구  소음 평균(dB)        1.000000       -0.137678
     진동(x) 평균(mm/s)  -0.137678        1.000000
영등포구 소음 평균(dB)        1.000000        0.086204
     진동(x) 평균(mm/s)   0.086204        1.000000
용산구  소음 평균(dB)        1.000000        0.007856
     진동(x) 평균(mm/s)   0.007856        1.000000
은평구  소음 평균(dB)        1.000000       -0.216914
     진동(x) 평균(mm/s)  -0.216914        1.000000
종로구  소음 평균(dB)        1.000000       -0.021070
     진동(x) 평균(mm/s)  -0.021070        1.000000
중구   소음 평균(dB)        1.000000       -0.034599
     진동(x) 평균(mm/s)  -0.034599        1.000000
중랑구  소음 평균(dB)        1.000000       -0.240771
     진동(x) 평균(mm/s)  -0.240771        1.000000

In [664]:
noise_avg

      자치구                   지역  소음 평균(dB)
0     강남구      industrial_area  54.367872
1     강남구          main_street  59.979620
2     강남구     residential_area  44.237804
3     강남구      roads_and_parks  60.376534
4     강남구  traditional_markets  46.352859
5     강동구      commercial_area  37.681979
6     강동구      industrial_area  44.831476
7     강동구          main_street  64.608498
8     강동구                parks  54.870833
9     강동구     residential_area  52.637484
10    강동구      roads_and_parks  58.995811
11    강동구  traditional_markets  44.417727
12    강북구      commercial_area        NaN
13    강북구                parks  53.672646
14    강북구     residential_area  46.727125
15    강북구      roads_and_parks  50.645708
16    강북구  traditional_markets  49.442623
17    강서구      commercial_area  64.433148
18    강서구      industrial_area  48.098012
19    강서구          main_street  63.619895
20    강서구     residential_area  46.272534
21    강서구      roads_and_parks  51.779412
22    강서구  traditional_markets  44.513539
23    관악구      commercial_area  50.912378
24    관악구      industrial_area  43.714387
25    관악구          main_street  58.537500
26    관악구     residential_area  46.351689
27    관악구      roads_and_parks  50.087121
28    관악구  traditional_markets  49.207376
29    광진구      commercial_area  36.011127
30    광진구          main_street  53.198324
31    광진구     residential_area  46.033142
32    광진구      roads_and_parks  56.428524
33    광진구  traditional_markets  48.618147
34    구로구      commercial_area  43.547354
35    구로구      industrial_area  49.363701
36    구로구     residential_area  46.587085
37    구로구      roads_and_parks  64.009825
38    구로구  traditional_markets  43.542159
39    금천구      commercial_area  54.082569
40    금천구      industrial_area  44.265349
41    금천구    public_facilities  42.854991
42    금천구     residential_area  45.145569
43    금천구      roads_and_parks  47.900566
44    노원구      commercial_area  55.290141
45    노원구      industrial_area  41.417980
46    노원구     residential_area  47.441744
47    노원구      roads_and_parks  53.483388
48    노원구  traditional_markets  40.440559
49    도봉구      commercial_area  55.677330
50    도봉구      industrial_area  44.873093
51    도봉구          main_street  58.319328
52    도봉구     residential_area  46.240943
53    도봉구      roads_and_parks  56.365379
54    도봉구  traditional_markets  42.130545
55   동대문구      commercial_area  50.387232
56   동대문구     residential_area  43.950136
57   동대문구      roads_and_parks  64.133142
58    동작구      commercial_area  47.602241
59    동작구      industrial_area  41.631944
60    동작구     residential_area  49.834881
61    동작구      roads_and_parks  53.865034
62    동작구  traditional_markets  48.696681
63    마포구      commercial_area  53.542420
64    마포구      industrial_area  45.220828
65    마포구          main_street  58.286396
66    마포구     residential_area  46.282695
67    마포구      roads_and_parks  59.331198
68    마포구  traditional_markets  43.519023
69   서대문구      commercial_area  43.944367
70   서대문구    public_facilities  55.330556
71   서대문구     residential_area  45.299644
72   서대문구      roads_and_parks  55.481826
73   서대문구  traditional_markets  54.081250
74    서초구      commercial_area  54.668985
75    서초구      industrial_area  42.084722
76    서초구          main_street  65.494725
77    서초구     residential_area  48.368425
78    서초구      roads_and_parks  51.488952
79    성동구      commercial_area  50.299539
80    성동구      industrial_area  47.712696
81    성동구          main_street  50.911111
82    성동구                parks  59.431280
83    성동구     residential_area  46.300340
84    성동구      roads_and_parks  69.519444
85    성북구      commercial_area        NaN
86    성북구      industrial_area  55.333333
87    성북구     residential_area  46.175286
88    성북구      roads_and_parks  56.662031
89    송파구      commercial_area  47.456963
90    송파구      industrial_area  49.444600
91    송파구                parks  56.458702
92    송파구     residential_area  45.539227
93    송파구      roads_and_parks  55.041511
94    송파구  traditional_markets  55.723120
95    양천구      commercial_area  48.544056
96    양천구      industrial_area  47.086254
97    양천구          main_street  62.951389
98    양천구     residential_area  45.073754
99    양천구      roads_and_parks  60.277256
100   양천구  traditional_markets  43.305809
101  영등포구      commercial_area  48.353025
102  영등포구      industrial_area  46.859064
103  영등포구     residential_area  44.738684
104  영등포구      roads_and_parks  57.038573
105   용산구      commercial_area  43.290682
106   용산구          main_street  55.645833
107   용산구     residential_area  44.650402
108   용산구      roads_and_parks  54.543994
109   은평구      commercial_area  53.950464
110   은평구          main_street  68.444290
111   은평구                parks  58.860918
112   은평구     residential_area  45.658660
113   은평구      roads_and_parks  57.898740
114   종로구          main_street  48.377358
115   종로구    public_facilities  45.353436
116   종로구     residential_area  45.610119
117   종로구      roads_and_parks  57.220747
118    중구      commercial_area  48.887500
119    중구      industrial_area  43.748495
120    중구          main_street  53.543488
121    중구     residential_area  44.114628
122    중구      roads_and_parks  49.374050
123   중랑구      commercial_area  43.994441
124   중랑구      industrial_area  62.243626
125   중랑구     residential_area  45.057493
126   중랑구      roads_and_parks  57.000697
127   중랑구  traditional_markets  41.863445

In [665]:
vibration_avg

     자치구  진동(x) 평균(mm/s)  진동(y) 평균(mm/s)  진동(z) 평균(mm/s)
0    강남구        0.026662        0.057145        1.012895
1    강동구        0.027618        0.055365        1.009232
2    강북구        0.027076        0.054171        1.032661
3    강서구        0.039025        0.052247        0.975779
4    관악구        0.026311        0.055569        1.029248
5    광진구        0.030016        0.061093        1.033652
6    구로구        0.028639        0.062395        0.996940
7    금천구        0.021555        0.054277        1.032154
8    노원구        0.026673        0.061946        0.981081
9    도봉구        0.024531        0.069954        1.027872
10  동대문구        0.028287        0.065255        1.042966
11   동작구        0.028672        0.066434        1.021227
12   마포구        0.030745        0.062877        1.031844
13  서대문구        0.027844        0.059305        1.029602
14   서초구        0.022566        0.067116        1.030665
15   성동구        0.027610        0.061040        1.028999
16   성북구        0.023872        0.059320        1.028074
17   송파구        0.028071        0.054081        1.011456
18   양천구        0.026882        0.056906        1.033087
19  영등포구        0.027498        0.058829        1.043955
20   용산구        0.022701        0.060523        1.026247
21   은평구        0.028896        0.058387        1.038420
22   종로구        0.029718        0.045098        1.037849
23    중구        0.021419        0.066447        0.995186
24   중랑구        0.031504        0.075951        1.032834

In [666]:
noise_avg.to_csv("noise_202411.csv", index=False, encoding="utf-8-sig")

In [667]:
vibration_avg.to_csv("vibration_avg_202411.csv", index=False, encoding="utf-8-sig")